<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.18" />
    <PackageReference Include="Svg.Controls.Skia.Avalonia" Version="11.3.6.2" />
    <PackageReference Include="ZLinq" Version="1.5.6" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SimEd.Common\SimEd.Common.csproj" />
  </ItemGroup>
</Project>
