<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <ApplicationIcon>SimEd.ico</ApplicationIcon>
    </PropertyGroup>

    <PropertyGroup>
        <PublishTrimmed>true</PublishTrimmed>
        <PublishAot>true</PublishAot>
        <OptimizationPreference>Speed</OptimizationPreference>
    </PropertyGroup>
    
    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.3.7" />
        <PackageReference Include="Avalonia.AvaloniaEdit" Version="11.3.0"/>
        <PackageReference Include="Avalonia.Desktop" Version="11.3.7" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.7" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.7" />
        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Include="Avalonia.Diagnostics" Version="11.3.7">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Avalonia.Themes.Simple" Version="11.3.7" />
        <PackageReference Include="Avalonia.Xaml.Interactions" Version="11.3.0.6" />
        <PackageReference Include="AvaloniaEdit.TextMate" Version="11.3.0"/>
        <PackageReference Include="AvaloniaEdit.TextMate.Grammars" Version="0.10.12" />
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0"/>
        <PackageReference Include="Dock.Avalonia" Version="11.3.6.4" />
        <PackageReference Include="Dock.Avalonia.Themes.Fluent" Version="11.3.6.4" />
        <PackageReference Include="Dock.Model.Avalonia" Version="11.3.6.4" />
        <PackageReference Include="Dock.Model.Mvvm" Version="11.3.6.4" />
        <PackageReference Include="Jab" Version="0.12.0" />
        <PackageReference Include="ReactiveUI" Version="22.1.1" />
        <PackageReference Include="StaticViewLocator" Version="0.1.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="TextMateSharp.Grammars" Version="1.0.70" />
		<PackageReference Include="Svg.Controls.Skia.Avalonia" Version="11.3.6.2" />
		<PackageReference Include="U8String" Version="0.16.0-alpha" />
        <PackageReference Include="ZLinq" Version="1.5.3" />

        <Reference Include="Avalonia.Themes.Simple"/>
    </ItemGroup>
    <ItemGroup>
        <Compile Update="Views\Solution\SolutionView.axaml.cs">
            <DependentUpon>MenuView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\SimEd.Common\SimEd.Common.csproj"/>
        <ProjectReference Include="..\SimEd.Models\SimEd.Models.csproj" />
    </ItemGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\Fonts\RobotoMono-SemiBold.ttf">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </AvaloniaResource>
        <AvaloniaResource Include="Assets\Fonts\Lexend-SemiBold.ttf">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </AvaloniaResource>
        <AvaloniaResource Include="Assets\Fonts\CascadiaCode-SemiBold.ttf">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </AvaloniaResource>
        <AvaloniaResource Include="Assets\Icons\csharp-original.svg">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </AvaloniaResource>
        <AvaloniaResource Include="Assets\Icons\csharp-original.png">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </AvaloniaResource>
        <AvaloniaResource Include="Assets\Icons\csharp-line.svg">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </AvaloniaResource>
        <AvaloniaResource Include="Assets\Icons\java-plain.svg">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </AvaloniaResource>
        <AvaloniaResource Include="Assets\Icons\pdb.svg">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </AvaloniaResource>
        <AvaloniaResource Include="Assets\Icons\square.svg">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </AvaloniaResource>
        <AvaloniaResource Include="Assets\Icons\folder.svg">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </AvaloniaResource>
        <AvaloniaResource Include="Assets\Icons\csproj.svg">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </AvaloniaResource>
        <AvaloniaResource Include="Assets\Icons\dll.svg">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </AvaloniaResource>
        <AvaloniaResource Include="Assets\Icons\python.svg">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </AvaloniaResource>
        <AvaloniaResource Include="Assets\Icons\brackets-svgrepo-com.svg">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </AvaloniaResource>
        <AvaloniaResource Include="Assets\Icons\sln-svgrepo-com.svg">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </AvaloniaResource>
        <AvaloniaResource Include="Assets\Icons\settings-svgrepo-com.svg">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </AvaloniaResource>
        <AvaloniaResource Include="Assets\Icons\markdown-svgrepo-com.svg">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </AvaloniaResource>
    </ItemGroup>
</Project>
